title = "dbz PyTorch"
use_rc = false
use_v2=true
[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = "0"
loadpretrainedmodel = false
random_seed = true
pretrainedmodelpath='/mnt/data9/Lipreading-DenseNet3D-master/weights/try__virus-fungus-bacteria-chlamydia-mycoplasma-100-2048-2-rc:False-forest:True.pt'
#pretrainedmodelpath ='/mnt/data9/Lipreading-DenseNet3D-master/weights/ipt_dfn-100-1024-2:65.pt'
#pretrainedmodelpath ='/mnt/data9/Lipreading-DenseNet3D-master/weights/ipt_dfn-onlyd-100-1024-2:62.pt'
#pretrainedmodelpath ='/mnt/data9/Lipreading-DenseNet3D-master/weights/ipt_baseline-resnet.pt'
use_3d = false
use_lstm=false
use_slice=true
use_plus=false
use25d=false
plus_as_input=false
mod='dbz'#'ab 
class_num=5
clinic=false
mc=false 
stacked=false

[input]
batchsize = 64
numworkers = 8
shuffle = true
croped = true
filtered = true

[model]
type = "Finetune-label"
inputdim = 256
hiddendim = 256
#class_num = 6
numlstms = 2
subcls=true
forest=true 
nf=1024
nc=2
nc2=3
nt=50

[training]
train = true
epochs = 21
startepoch = 10
statsfrequency = 100
data_root = ''#useless and used as ages_gender.txt path
index_root = 'data/txt/croped_filted_train2.txt'
padding = 35
learningrate = 1e-4
momentum = 0.95
weightdecay = 0.0005
save_prefix = "weights/ablation"

[validation]
validate = true
data_root = ''
index_root = 'data/txt/croped_filted_val.txt'
padding = 35#45
saveaccuracy = false
saves='re/ablation-2048.npy'

[test]
test = true
data_root = 'G'
index_root = ''
padding = 35
topk=3
saveaccuracy = false
