title = "dbz PyTorch"
use_rc = true

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = "1"
loadpretrainedmodel = false
random_seed = true
pretrainedmodelpath ='saves/good_50-1024-4.pt'
use_3d = false
use_lstm=false
use_slice=true
use_plus=false
use25d=false
plus_as_input=false
mod='dbz'#'ab 
class_num=5
clinic=false
mc=false 
stacked=false

[input]
batchsize = 128
numworkers = 16
shuffle = true
croped = true
filtered = true

[model]
type = "Finetune-label"
inputdim = 256
hiddendim = 256
#class_num = 6
numlstms = 2
subcls=true
forest=true #############################
nf=1600
nc=4
nt=30

[training]
train = true
epochs = 11
startepoch = 0
statsfrequency = 100
data_root = ''#useless and used as ages_gender.txt path
index_root = 'data/txt/pos_map_train.txt'
padding = 35
learningrate = 1e-4
momentum = 0.99
weightdecay = 0.0001
save_prefix = "weights/try_{}"

[validation]
validate = true
data_root = ''
index_root = 'data/txt/croped_filted_val.txt'
padding = 80#45
saveaccuracy = false
saves='re/dbz_{}.npy'

[test]
test = true
data_root = 'G'
index_root = ''
padding = 80
topk=5
saveaccuracy = false
