title = "dbz PyTorch"
use_rc = false
use_v2=true
[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = "1"
loadpretrainedmodel = false
random_seed = true
pretrainedmodelpath='/mnt/data9/Lipreading-DenseNet3D-master/weights//mnt/data9/Lipreading-DenseNet3D-master/weights/covid__healthy-CAP-AB-in-COVID-19-10-2048-4-rc:False-forest:True.pt'
#pretrainedmodelpath ='/mnt/data9/Lipreading-DenseNet3D-master/weights/ipt_dfn-100-1024-2:65.pt'
#pretrainedmodelpath ='/mnt/data9/Lipreading-DenseNet3D-master/weights/ipt_dfn-onlyd-100-1024-2:62.pt'
#pretrainedmodelpath ='/mnt/data9/Lipreading-DenseNet3D-master/weights/ipt_baseline-resnet.pt'
use_3d = false
use_lstm=false
use_slice=true
use_plus=false
use25d=false
plus_as_input=false
mod='all'#'ab 
class_num=4
clinic=false
mc=false 
stacked=false

[input]
batchsize = 180
numworkers = 16
shuffle = true
croped = true
filtered = true

[model]
type = "Finetune-label"
inputdim = 256
hiddendim = 256
#class_num = 6
numlstms = 2
subcls=true
forest=true 
nf=2048
nc=3
nc2=3
nt=50

[training]
train = true
epochs = 21
startepoch = 10
statsfrequency = 100
data_root = ''#useless and used as ages_gender.txt path
index_root = 'data/txt/train_allin.txt'
padding = 35
learningrate = 5e-5
momentum = 0.95
weightdecay = 0.001
save_prefix = "weights/covid_{}"

[validation]
validate = false
data_root = ''
index_root = 'data/txt/train_allin.txt'
padding = 35#45
saveaccuracy = false
saves='re/covid.npy'

[test]
test = true
data_root = 'G'
index_root = ''
padding = 35
topk=3
saveaccuracy = false
