title = "covid19 PyTorch 3D"

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = "6"
loadpretrainedmodel = false
random_seed = true
pretrainedmodelpath = 'weights/3d_3cls.pt'
use_3d = true
use_lstm=true
use_slice=false
use_plus=false
class_num=3
use25d=false
plus_as_input=false

[input]
batchsize = 4
numworkers = 4
shuffle = true

[model]
type = "Finetune-label"
inputdim = 256
hiddendim = 256
numclasses = 2
numlstms = 2
z_length=5

[training]
train = true
epochs = 80
startepoch = 0
statsfrequency = 100
data_root = ''#useless and used as ages_gender.txt path
index_root = 'data/3cls_train.list'
seg_root='/home/cwx/extra/covid_project_segs/lungs'
padding = 45
learningrate = 1e-6
momentum = 0.95
weightdecay = 0.05
save_prefix = "weights/3D_3cls"

[validation]
validate = true
data_root = ''
seg_root='/home/cwx/extra/covid_project_segs/lungs'
index_root = 'data/3cls_test.list'
padding = 45
saveaccuracy = false


[test]
test = false
data_root = '/mnt/data6/lung_jpgs_with_SEG'
index_root = 'data/txt/2train_lidc_ild_train.txt'
padding = 45
saveaccuracy = false
